### PR TITLE
Fix: Snake should have a body

### LINKED ISSUE #6: Snake should have a body
The snake from the `animal snake` command should have a body, that's the most fun part of snakes!

### PR DESCRIPTION
**Pull request by itsfrank**
## Summary

This PR implements the changes described in #6.

## Issue Description

The snake from the `animal snake` command should have a body, that's the most fun part of snakes!

---

Closes #6

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -59,11 +59,13 @@ fn main() {
...
-                println!(" \\~~~~~/");
-                println!("  |||||");
+                println!("      ____");
+                println!("     /    \\");
+                println!("    (  o o  )");
+                println!("     \\~~~~~/");
+                println!("   __||||||||__");
+                println!("  /            \\");
+                println!(" (______________)")
             }
```
Comment (itsfrank) [inline src/main.rs]: this is no good, the body needs to be long and snakey! It's fine to completely change the snake design in order to have a long curly snakey body

**Comment by itsfrank** [comment]
Also, let's add an alias for `snake` called `snek`

**Comment by itsfrank** [comment]
**Auto-patcher** is starting work on this PR.

I will:
1. Clone the repository
2. Checkout the existing branch `agent/issue-6`
3. Address review comments and feedback
4. Push changes to update the PR

This may take a few minutes. I'll update this comment when done.

**Comment by itsfrank** [comment]
󰚩 **Auto-patcher** is starting work on this issue.

I will:
1. Clone the repository
2. Create branch `agent/issue-7`
3. Implement the necessary changes
4. Create a pull request

This may take a few minutes. I'll update this comment when done.

**Comment by itsfrank** [comment]
󰅖 **Auto-patcher** encountered an error while processing this issue.

Error: Label does not exist - https://docs.github.com/rest/issues/labels#remove-a-label-from-an-issue

The `agent-ready` label has been removed. Please review the issue and try again.

**Comment by itsfrank** [comment]
**Auto-patcher** was interrupted while processing this PR.

The operation was cancelled and the working directory has been cleaned up. The "agent-working" label has been removed.

To retry, please add the "agent-ready" label again.

**Comment by itsfrank** [comment]
**Auto-patcher** was interrupted while processing this PR.

The operation was cancelled and the working directory has been cleaned up. The "agent-working" label has been removed.

To retry, please add the "agent-ready" label again.

**Comment by itsfrank** [comment]
**Auto-patcher** is starting work on this PR.

I will:
1. Clone the repository
2. Checkout the existing branch `agent/issue-6`
3. Address review comments and feedback
4. Push changes to update the PR

This may take a few minutes. I'll update this comment when done.

**Comment by itsfrank** [comment]
**Auto-patcher** has completed work on this PR.

✅ Repository cloned
✅ Branch `agent/issue-6` checked out
✅ Changes implemented to address review feedback
✅ Changes pushed to update PR

Please review the updated changes.
